sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in fib-k8s-248814-3da67c9cfcc1.json.enc -out fib-k8s-248814-3da67c9cfcc1.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file fib-k8s-248814-3da67c9cfcc1.json
  - gcloud config set project fib-k8s-248814
  - gcloud config set compute/zone southamerica-east1-c
  - gcloud container clusters get-credentials fib-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "#DOCKER_USERNAME" --password-stdin
  - docker build -t joseluisjb1990/react-test -t ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true joseluisjb1990/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master