apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-testing-com-tls
spec:
  secretName: k8s-testing-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-testing.com
  dnsNames:
    - k8s-testing.com
    - www.k8s-testing.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s-testing.com
          - www.k8s-testing.com